### ISSUE TITLE
Lines with missing coverage

### ISSUE THREAD

**Issue by fredrikaverpil** [irongut/CodeCoverageSummary#113]
## Feature Request

I'd love to see a new table column containing ranges of uncovered lines for the given file, like for example: 1-14, 54-77, 104-105.

Something very useful would then also be if they were linked, so I could click them and be taken to each range of lines, highlighted.

**Comment by JoA-MoS** [comment]
@fredrikaverpil - did you consider https://github.com/marketplace/actions/code-coverage-report. I ran into an issue using that action as the links and markup eventually exceeded the max PR comment length but it does exactly what you ask.

**Comment by fredrikaverpil** [comment]
@JoA-MoS awesome, your suggestion works great! 🎉 
Thank you! 🙇
