### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by ghost** [irongut/CodeCoverageSummary#168]
## Bug Report
`
Pull down action image 'ghcr.io/irongut/codecoveragesummary:v1.3.0'
  /usr/bin/docker pull ghcr.io/irongut/codecoveragesummary:v1.3.0
  Error response from daemon: Head "https://ghcr.io/v[2](https://github.com/alignedcode/acvod-tv/actions/runs/4817930042/jobs/8579527012#step:2:2)/irongut/codecoveragesummary/manifests/v1.[3](https://github.com/alignedcode/acvod-tv/actions/runs/4817930042/jobs/8579527012#step:2:3).0": Get "https://ghcr.io/token?scope=repository%3Airongut%2Fcodecoveragesummary%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning: Docker pull failed with exit code 1, back off 7.183 seconds before retry.
  /usr/bin/docker pull ghcr.io/irongut/codecoveragesummary:v1.3.0
  Error response from daemon: Head "https://ghcr.io/v2/irongut/codecoveragesummary/manifests/v1.3.0": Get "https://ghcr.io/token?scope=repository%3Airongut%2Fcodecoveragesummary%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning: Docker pull failed with exit code 1, back off [7](https://github.com/alignedcode/acvod-tv/actions/runs/4817930042/jobs/8579527012#step:2:7).207 seconds before retry.
  /usr/bin/docker pull ghcr.io/irongut/codecoveragesummary:v1.3.0
  Error: The operation was canceled.
`
![image](https://user-images.githubusercontent.com/127767359/234818268-c9768622-4f1f-406f-b452-bc0c4ff9841e.png)

**Comment by kamransaleem** [comment]
+1 for this issue

**Comment by Scooletz** [comment]
I just bought 32 coffee cups as in the sponsor section is stated that 5$

> At this tier I can make 16 cups

I hope this helps a bit 🙇
