### ISSUE TITLE
Option to show badge only

### ISSUE THREAD

**Issue by chitran96** [irongut/CodeCoverageSummary#174]
## Feature Request

Sometimes we need to show badges only and check build log for detail result, since our code base is big and output all result create a super big comment which is hard to scroll down.

### Expected Behaviour
Only output badge to output file

### Additional Context
Add any other context about the feature here.

### Linked To
List any issues linked to this feature request.

**Comment by lukasrgr** [comment]
@chitran96 is it possible with the fix, mentioned in #175, to show only the badge?
