### ISSUE TITLE
Grouping of results

### ISSUE THREAD

**Issue by ScottGuymer** [irongut/CodeCoverageSummary#197]
## Feature Request

When specifying multiple files in the `filename` value it would be great to have a grouping of the results by the results file rather than as one large block. We have a monorepo with many test results and it just too long of a comment on the PR.

It would also be great to show a total per group and collapse the main results to save on space.

### Expected Behaviour

The markdown/text output should show the results grouped per file to look something like

![image](https://github.com/irongut/CodeCoverageSummary/assets/956825/eb13fa7f-db28-43ff-96e3-057376b889fd)

You could also have collapsed results like this

![image](https://github.com/irongut/CodeCoverageSummary/assets/956825/a5064d7a-af38-4e60-839d-21237190732a)

![image](https://github.com/irongut/CodeCoverageSummary/assets/956825/f88db870-86ea-4eaa-860f-dd6a3728dead)

**Comment by Phxntxm** [comment]
Pls no stale bot, I really want this feature (Especially the collapsability part)

**Comment by grumpyoldman-io** [comment]
I also want this feature lil' bot!

**Comment by Phxntxm** [comment]
Is there no way to tag this to make sure it doesn't turn stale?
