### ISSUE TITLE
What does complexity mean?

### ISSUE THREAD

**Issue by laserprec** [irongut/CodeCoverageSummary#20]
## Feature Request

Hi there! Great tool you are building here! Much appreciated. Looking at the documentation in the README.md, the example output has a measure of  `complexity`:

```
Company.Example: Line Rate = 83%, Branch Rate = 69%, Complexity = 671, ✔
Company.Example.Library: Line Rate = 27%, Branch Rate = 100%, Complexity = 11, ❌
Summary: Line Rate = 83% (1212 / 1460), Branch Rate = 69% (262 / 378), Complexity = 682, ✔
Minimum allowed line rate is 50% 
````

I am wondering what does it mean and how it is measured? 

The reason I am asking is because I ran the coverage report for the first time in my repo and I have zeroes for the `Branch Rate` and `Complexity` (please see the following). I am not sure if this is by design or I did something wrong.

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
some.package.a| 77% | 0% | 0 | ✔
some.package.b| 20% | 0% | 0 | ❌
**Summary** | **80%** (80 / 100) | **0%** (0 / 0) | 0 | ✔

### Expected Behaviour

It would be great if the documentation can be updated on `complexity` and `branch rate` as well.

Thanks!

**Comment by irongut** [comment]
@laserprec I've just released CodeCoverageSummary v1.2.0 which includes support for hiding the Branch Rate and Complexity values. I've also included an [explanation of the values](https://github.com/irongut/CodeCoverageSummary/wiki/What-do-the-coverage-values-mean%3F) in the project wiki.
