### ISSUE TITLE
Publish releases to GitHub Container Registry

### ISSUE THREAD

**Issue by Casey-Kiewit** [irongut/CodeCoverageSummary#4]
## Feature Request
I'd love if you were able to publish this action to GitHub Marketplace. Published actions provide significant time savings for workflows since the container doesn't have to be built from scratch on every run.

In our workflows, the "publish unit tests result" action we use takes around 3 seconds to pull from the marketplace, whereas this action takes around 37 seconds to build from scratch.

### Expected Behaviour
`N/A`

### Additional Context
GitHub Documentation:
https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

Another Project That Makes Use Of This:
https://github.com/EnricoMi/publish-unit-test-result-action

### Linked To
`N/A`

**Comment by irongut** [comment]
@Casey-Kiewit I've just published v1.0.2 which uses a pre-built container on GHCR like the other action. If you update to the latest version you should see an improvement in execution time.
