### ISSUE TITLE
Get "Parse Error: Input string was not in a correct format." with MATLAB's Cobertura format code coverage file

### ISSUE THREAD

**Issue by rpurser47** [irongut/CodeCoverageSummary#46]
## Bug Report

Using a Cobertura XML report generated by [MATLAB](https://www.mathworks.com/help/matlab/ref/matlab.unittest.plugins.codecoverageplugin-class.html#mw_2e79c48c-5bb3-40c6-8fb2-d2efd3ce6b72) gives a "Parse Error: Input string was not in a correct format."  Seems very similar to issue #9 .  I suspect that MATLAB is not outputting something in the XML that you expect. 

### Workflow File
```yaml
     # Publish code coverage results
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: report/coverage.xml     
          badge: true
          format: markdown
```

### Actions Log
```
0s
Run irongut/CodeCoverageSummary@v[1](https://github.com/mathworks/climatedatastore/runs/7053609696?check_suite_focus=true#step:8:1).2.0
/usr/bin/docker run --name ghcrioirongutcodecoveragesummaryv[12](https://github.com/mathworks/climatedatastore/runs/7053609696?check_suite_focus=true#step:8:13)0_c10c9f --label 72882e --workdir /github/workspace --rm -e INPUT_FILENAME -e INPUT_BADGE -e INPUT_FORMAT -e INPUT_FAIL_BELOW_MIN -e INPUT_HIDE_BRANCH_RATE -e INPUT_HIDE_COMPLEXITY -e INPUT_INDICATORS -e INPUT_OUTPUT -e INPUT_THRESHOLDS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/climatedatastore/climatedatastore":"/github/workspace" ghcr.io/irongut/codecoveragesummary:v1.2.0  "--files" "report/coverage.xml" "--badge" "true" "--fail" "false" "--format" "markdown" "--hidebranch" "false" "--hidecomplexity" "false" "--indicators" "true" "--output" "console" "--thresholds" "50 75"
Code Coverage File: report/coverage.xml
Parse Error: Input string was not in a correct format.
Error: System.NullReferenceException - Object reference not set to an instance of an object.
```

### Expected Behavior
A coverage report

### Additional Context
I [attached a .txt file](https://github.com/irongut/CodeCoverageSummary/files/8984773/MATLAB.coverage.txt) with the XML generated by MATLAB that's supposed to be Cobertura format.  If you feel that the MATLAB XML generated is in error, please let me know and I'll file a bug report with the MATLAB team.

### Linked To
[Related issue in my repo](https://github.com/mathworks/climatedatastore/issues/9)

**Comment by rpurser47** [comment]
Our development team looked at this, and noted that MATLAB generates NaNs for several values in the report, rather than zeros.  Building on that, I added a step to my YAML that does

`sed 's/NaN/0/g' MATLAB.coverage.xml > MATLAB.coverage.zeros.xml`

replacing all NaNs with 0s in the file.  Once that's done, your report is correctly generated. 

Your call whether that's our tool not meeting the standard, or your tool not being permissive enough.  Personally, I suspect that we shouldn't be generating NaNs.

**Comment by irongut** [comment]
@rpurser47 Apologies for the delay responding. Unfortunately the [Cobertura DTD](https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd) gives no guidance for data types or possible values.

Looking at your example output there is no branch data. If that is because the code tested has no branches then the branch rate should be 1. If it is because your tool doesn't test for branches then NaN is probably appropriate.

The more I think about it, the more I'm thinking I should allow NaN values for branch and complexity.

**Comment by rpurser47** [comment]
No worries.  We put NaN in for values that we don't compute.  As you say, it's probably best to allow them as indicators that it was not computed.

All the best,
-Rob
