### ISSUE TITLE
Workflow unable to pull Docker image to run action

### ISSUE THREAD

**Issue by fjmorel** [irongut/CodeCoverageSummary#6]
## Bug Report

Most of the times that my actions run, I get the error in the log below and then the rest of the workflow fails.

edit: sometimes it works, so maybe this is an issue with some runners?

### Workflow File
```yaml
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.0.2
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'
```

### Actions Log
```
Pull down action image 'ghcr.io/irongut/codecoveragesummary:v1.0.2'
  /usr/bin/docker pull ghcr.io/irongut/codecoveragesummary:v1.0.2
  Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
  Warning: Docker pull failed with exit code 1, back off 6.596 seconds before retry.
  /usr/bin/docker pull ghcr.io/irongut/codecoveragesummary:v1.0.2
  Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
  Warning: Docker pull failed with exit code 1, back off 8.36 seconds before retry.
  /usr/bin/docker pull ghcr.io/irongut/codecoveragesummary:v1.0.2
  Error response from daemon: Head "ghcr.io/v2/irongut/codecoveragesummary/manifests/v1.0.2": received unexpected HTTP status: 503 Service Unavailable
Error: Docker pull failed with exit code 1
```

### Expected Behavior
Actions is able to pull the Docker image for this action and run my entire workflow.

### Additional Context
I first noticed it today. It was fine on Friday.

**Comment by irongut** [comment]
@fjmorel I've just tried one of my pipelines and it didn't have any problems pulling the container. There was a [service incident](https://www.githubstatus.com/incidents/vlbr8z458fq0) for GitHub Packages earlier today which was probably the problem you experienced.

If there is an extended outage for Packages you could try the previous version of the action (v1.0.1) which doesn't use the cached container. Your workflow will take 30 seconds longer to run but the action has almost the same output.

**Comment by fjmorel** [comment]
Ah, I didn't see that. Thank you for looking into it!
